### ISSUE TITLE
GNUS - needless keybind

### ISSUE THREAD

**Issue by orgcandman** [redguardtoo/mastering-emacs-in-one-year-guide#70]
'l' and 'L' exist in the Group view to manipulate the displayed groups. So, your 'o' keybind isn't needed. Worse, it interferes with reconnect, iirc.

**Comment by redguardtoo** [comment]
'l' and 'L' won't display a group which containing NO unread mails. It's mentioned several times in the article.

It's totally fine to use other keybinding instead of 'o'. I use erc, so `o` is OK for me.

I spent about 7 hours to reading the Gnus manual from the beginning to the end before I picking out the essential 5%.

**Comment by orgcandman** [comment]
I just tested - 'L' works just fine; This is with emacs from master branch a few weeks ago.

**Comment by redguardtoo** [comment]
Maybe emacs developers changed the default setup. I checked the documentation on Emacs 24.3, my solution is correct. Anyway, I already explain the the key point of the issue is the level passed to `gnus-group-list-groups`, keybinding is just the trivial thing.

Documentation on `l`
```
l runs the command gnus-group-list-groups, which is an interactive
autoloaded compiled Lisp function in `gnus-group.el'.

It is bound to l, A s, <menu-bar> <Groups> <Listing> <List unread
subscribed groups>.

(gnus-group-list-groups &optional LEVEL UNREAD LOWEST)

List newsgroups with level LEVEL or lower that have unread articles.
Default is all subscribed groups.
If argument UNREAD is non-nil, groups with no unread articles are also
listed.

Also see the `gnus-group-use-permanent-levels' variable.

[back]
```

Documentation on `L`,
```
L runs the command gnus-group-list-all-groups, which is an interactive
compiled Lisp function in `gnus-group.el'.

It is bound to L, A u, <menu-bar> <Groups> <Listing> <List
(un)subscribed groups>.

(gnus-group-list-all-groups &optional ARG)

List all newsgroups with level ARG or lower.
Default is `gnus-level-unsubscribed', which lists all subscribed and most
unsubscribed groups.

```
